# Generated by Django 5.2.7 on 2026-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
